Adds documentation for Access + RFD40
Coppernic/coppernic.github.io pull request #10
Opened 2023-05-04 09:37 UTC by FlorentYvinec

2023-05-05 16:00 UTC, Kamelovitch requested changes

2023-05-09 02:29 UTC, FlorentYvinec commented on docs/product/access-rfd40.md
> +Zebra sample code adapted with Coppernic SDK can be found [here](https://gitlab.com/Coppernic/Android/External/123rfid_mobile). Access to this sample is limited, please contact support@coppernic.com
@Kamelovitch  Ca ne marche pas l'adresse  support@coppernic.com ?

2023-05-09 07:12 UTC, mreynier approved these changes

2023-05-09 08:46 UTC, FlorentYvinec commented on docs/product/access-rfd40.md
> +Zebra sample code adapted with Coppernic SDK can be found [here](https://gitlab.com/Coppernic/Android/External/123rfid_mobile). Access to this sample is limited, please contact support@coppernic.fr
```suggestion
Zebra sample code adapted with Coppernic SDK can be found [here](https://gitlab.com/Coppernic/Android/External/123rfid_mobile). Access to this sample is limited, please contact [Coppernic Support](mailto://support@coppernic.fr)
```

2023-05-09 08:47 UTC, merged